app/app/home/forms.py
# coding:utf8
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, FileField, TextAreaField
from wtforms.validators import DataRequired, EqualTo, Email, Regexp, ValidationError

from app.models import User


class RegistForm(FlaskForm):
    name = StringField(
        label="昵称",
        validators=[DataRequired("请输入昵称！")],
        description="昵称",
        render_kw={
            'class': "form-control input-lg",
            'placeholder': "请输入昵称！",
        })

    email = StringField(
        label="邮箱",
        validators=[
            DataRequired("请输入邮箱！"),
            Email("邮箱格式不正确")
        ],
        description="邮箱",
        render_kw={
            'class': "form-control input-lg",
            'placeholder': "请输入邮箱！",
        })
    phone = StringField(
        label='手机号码',
        validators=[
            DataRequired(";请输入手机号码"),
            Regexp("1\d{10}$", message='手机格式不正确！')
        ],
        description="手机号码",
        render_kw={
            'class': "form-control input-lg",
            'placeholder': '请输入手机号码'
        }
    )
    pwd = PasswordField(
        label="密码",
        validators=[
            DataRequired("请输入密码！")
        ],
        description="密码",
        render_kw={
            'class': "form-control input-lg",
            'placeholder': "请输入密码！",
        })

    re_pwd = PasswordField(
        label="确认密码",
        validators=[
            DataRequired("请确认密码！"),
            EqualTo('pwd', message='两次密码不一致')
        ],
        description="确认密码",
        render_kw={
            'class': "form-control input-lg",
            'placeholder': "请确认密码！",
        })

    submit = SubmitField(
        '提交注册',
        render_kw={
            'class': "btn btn-lg btn-success btn-block"
        })

    def validate_name(self, field):
        name = field.data
        user = User.query.filter_by(
            name=name
        ).count()
        if user == 1:
            raise ValidationError("用户名已存在")

    def validate_email(self, field):
        email = field.data
        user = User.query.filter_by(
            email=email
        ).count()
        if user == 1:
            raise ValidationError("邮箱已存在")

    def validate_phone(self, field):
        phone = field.data
        user = User.query.filter_by(
            phone=phone
        ).count()
        if user == 1:
            raise ValidationError("手机号码已存在")


class LoginForm(FlaskForm):
    name = StringField(
        label="昵称",
        validators=[DataRequired("请输入昵称！")],
        description="昵称",
        render_kw={
            'class': "form-control",
            'placeholder': "请输入昵称！",
        })
    pwd = PasswordField(
        label="密码",
        validators=[
            DataRequired("请输入密码！")
        ],
        description="密码",
        render_kw={
            'class': "form-control",
            'placeholder': "请输入密码！",
        })
    submit = SubmitField(
        '登录',
        render_kw={
            'class': "btn btn-lg btn-success btn-block"
        })

    def validate_name(self, field):
        name = field.data
        user = User.query.filter_by(
            name=name
        ).count()
        if user == 0:
            raise ValidationError("用户名不存在!")


class UserdetailForm(FlaskForm):
    name = StringField(
        label="昵称",
        validators=[DataRequired("请输入昵称！")],
        description="昵称",
        render_kw={
            'class': "form-control input-lg",
            'placeholder': "请输入昵称！",
        })
    email = StringField(
        label="邮箱",
        validators=[
            DataRequired("请输入邮箱！"),
            Email("邮箱格式不正确")
        ],
        description="邮箱",
        render_kw={
            'class': "form-control input-lg",
            'placeholder': "请输入邮箱！",
        })
    phone = StringField(
        label='手机号码',
        validators=[
            DataRequired(";请输入手机号码"),
            Regexp("1\d{10}$", message='手机格式不正确！')
        ],
        description="手机号码",
        render_kw={
            'class': "form-control input-lg",
            'placeholder': '请输入手机号码'
        })
    face = FileField(
        label="头像",
        validators=[DataRequired("请上传头像！")],
        description="头像")

    info = TextAreaField(
        label="简介",
        validators=[DataRequired("请输入简介！")],
        description="简介",
        render_kw={
            'class': "form-control",
            "rows": 10
        })

    submit = SubmitField(
        '保存修改',
        render_kw={
            'class': "btn btn-success"
        })


class PwdForm(FlaskForm):
    old_pwd = PasswordField(
        label="旧密码",
        validators=[
            DataRequired("请输入旧密码！")
        ],
        description="旧密码",
        render_kw={
            'class': "form-control",
            'placeholder': "请输入旧密码！",
        })
    new_pwd = PasswordField(
        label="新密码",
        validators=[
            DataRequired("请输入新密码！")
        ],
        description="新密码",
        render_kw={
            'class': "form-control",
            'placeholder': "请输入新密码！",
        })
    submit = SubmitField(
        '提交',
        render_kw={
            'class': "btn btn-success"
        })

    def validate_old_pwd(self, field):
        from .views import exist
        pwd = field.data
        user = User.query.filter_by(
            id=exist['user_id']
        ).first()
        if not user.check_pwd(pwd):
            raise ValidationError("旧密码错误！")


class CommentForm(FlaskForm):
    content = TextAreaField(
        label="评论内容",
        validators=[
            DataRequired('发表你的评论！')
        ],
        description="评论内容",
        render_kw={
            'id': "input_content"
        }
    )
    submit = SubmitField(
        '提交评论',
        render_kw={
            'class': "btn btn-success",
            'id': "btn-sub"
        })

app/app/home/__init__.py
# coding:utf8
from flask import Blueprint

home = Blueprint("home", __name__)

import app.home.views

app/app/home/views.py
# coding:utf8
import datetime
import os
import uuid
from functools import wraps

from flask import render_template, redirect, url_for, flash, request
from werkzeug.security import generate_password_hash
from werkzeug.utils import secure_filename

from app import app
from app.models import User, Userlog, Preview, Tag, Comment, Movie, Moviecol
from app.models import db
from . import home
from .forms import RegistForm, LoginForm, UserdetailForm, PwdForm, CommentForm

exist = {}


# 修改文件名称
def change_filename(filename):
    fileinfo = os.path.splitext(filename)
    filename = datetime.datetime.now().strftime("%Y%m%d%H%M%S") + str(uuid.uuid4().hex) + fileinfo[-1]
    return filename


def user_login_req(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'user' not in exist:
            return redirect(url_for('home.login', next=request.url))
        return f(*args, **kwargs)

    return decorated_function


@home.route("/layout")
def layout():
    render_template("home/layout.html", exist=exist)


@home.route("/<int:page>/", methods=['GET'])
def index(page=None):
    if page is None:
        page = 1
    tags = Tag.query.all()
    page_data = Movie.query
    # 标签筛选
    tid = request.args.get("tid", 0)
    if int(tid) != 0:
        page_data = page_data.filter_by(
            tag_id=int(tid)
        )
    # 星级筛选
    star = request.args.get("star", 0)
    if int(star) != 0:
        page_data = page_data.filter_by(
            star=int(star)
        )
    # 时间筛选
    time = request.args.get("time", 0)
    if int(time) != 0:
        if int(time) == 1:
            page_data = page_data.order_by(
                Movie.addtime.desc()
            )
        else:
            page_data = page_data.order_by(
                Movie.addtime.asc()
            )
    # 播放量筛选
    pm = request.args.get("pm", 0)
    if int(pm) != 0:
        if int(pm) == 1:
            page_data = page_data.order_by(
                Movie.playnum.desc()
            )
        else:
            page_data = page_data.order_by(
                Movie.playnum.asc()
            )
    # 评论数量筛选
    cm = request.args.get("cm", 0)
    if int(cm) != 0:
        if int(cm) == 1:
            page_data = page_data.order_by(
                Movie.commentnum.desc()
            )
        else:
            page_data = page_data.order_by(
                Movie.commentnum.asc()
            )

    page_data = page_data.paginate(page=page, per_page=10)

    p = dict(
        tid=tid,
        star=star,
        time=time,
        pm=pm,
        cm=cm
    )
    return render_template("home/index.html", tags=tags, p=p, page_data=page_data, exist=exist)


@home.route("/login", methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        data = form.data
        user = User.query.filter_by(name=data['name']).first()
        if not user.check_pwd(data['pwd']):
            flash("密码错误", 'error')
            return redirect(url_for("home.login"))
        exist['user'] = user.name
        exist["user_id"] = user.id
        userlog = Userlog(
            user_id=exist['user_id'],
            ip=request.remote_addr
        )
        db.session.add(userlog)
        db.session.commit()
        return redirect(url_for("home.index", page=1))
    return render_template("home/login.html", form=form)


@home.route("/logout")
def logout():
    exist.pop('user', None)
    exist.pop('user_id', None)
    return redirect(url_for("home.index", page=1))


# 会员注册
@home.route("/regist", methods=['GET', 'POST'])
def regist():
    form = RegistForm()
    if form.validate_on_submit():
        data = form.data
        # 验证注册时两次输入的密码是否相同
        if data['pwd'] != data['re_pwd']:
            flash("两次输入的密码不相同", 'error')
        elif data['pwd'] == data['re_pwd']:
            user = User(
                name=data['name'],
                email=data['email'],
                phone=data['phone'],
                pwd=generate_password_hash(data["pwd"]),
                uuid=uuid.uuid4().hex
            )
            db.session.add(user)
            db.session.commit()
            flash("注册成功！点击返回登录页面...", 'success')
    return render_template("home/regist.html", form=form)


# 会员中心
@home.route("/user", methods=['GET', 'POST'])
@user_login_req
def user():
    form = UserdetailForm()
    user = User.query.get(exist['user_id'])
    form.face.validators = []
    if request.method == 'GET':
        form.name.data = user.name
        form.email.data = user.email
        form.phone.data = user.phone
        form.info.data = user.info
    if form.validate_on_submit():
        data = form.data
        file_face = secure_filename(form.face.data.filename)
        if not os.path.exists(app.config["FC_DIR"]):
            os.makedirs(app.config["FC_DIR"])
            os.chmod(app.config["FC_DIR"], "rw")
        user.face = change_filename(file_face)
        form.face.data.save(app.config["FC_DIR"] + user.face)
        name_count = User.query.filter_by(name=data['name']).count()
        if name_count == 1 and data['name'] != user.name:
            flash("昵称已经存在！", 'error')
        email_count = User.query.filter_by(email=data['email']).count()
        if email_count == 1 and data['email'] != user.email:
            flash("邮箱已经存在！", 'error')
        phone_count = User.query.filter_by(phone=data['phone']).count()
        if phone_count == 1 and data['phone'] != user.phone:
            flash("手机号码已经存在！", 'error')
        user.name = data['name']
        user.email = data['email']
        user.phone = data['phone']
        user.info = data['info']

        db.session.add(user)
        db.session.commit()
        flash("修改成功", 'success')
        return redirect(url_for("home.user"))

    return render_template("home/user.html", form=form, user_data=user)


@home.route("/pwd", methods=['GET', 'POST'])
@user_login_req
def pwd():
    form = PwdForm()
    if form.validate_on_submit():
        data = form.data
        user = User.query.filter_by(name=exist['user']).first()
        from werkzeug.security import generate_password_hash
        user.pwd = generate_password_hash(data["new_pwd"])
        db.session.add(user)
        db.session.commit()
        flash("修改密码成功!请重新登陆！", 'success')
        return redirect(url_for("home.login"))
    return render_template("home/pwd.html", form=form)


@home.route("/comments/<int:page>", methods=['GET', 'POST'])
@user_login_req
def comments(page=None):
    if page is None:
        page = 1
    page_data = Comment.query.filter_by(
        user_id=int(exist['user_id'])
    ).order_by(
        Comment.addtime.desc()
    ).paginate(page=page, per_page=8)
    com_data = Comment.query.filter_by(user_id=int(exist['user_id']))

    for v in com_data:
        user_data = User.query.filter_by(id=int(exist['user_id']))
        movie_data = Movie.query.filter_by(id=int(v.movie_id))
    return render_template("home/comments.html", page_data=page_data, user_data=user_data, movie_data=movie_data)


# 会员登陆日志
@home.route("/loginlog/<int:page>/", methods=['GET', 'POST'])
@user_login_req
def loginlog(page=None):
    if page is None:
        page = 1
    page_data = Userlog.query.filter_by(
        user_id=int(exist['user_id'])
    ).order_by(
        Userlog.addtime.desc()
    ).paginate(page=page, per_page=8)

    return render_template("home/loginlog.html", page_data=page_data)


# 添加收藏
@home.route("/moviecol/add/", methods=['GET'])
@user_login_req
def moviecol_add():
    uid = request.args.get("uid", "")
    mid = request.args.get("mid", "")
    moviecol = Moviecol.query.filter_by(
        user_id=int(uid),
        movie_id=int(mid)
    ).count()
    if moviecol == 1:
        data = dict(ok=0)
    else:
        moviecol = Moviecol(
            user_id=int(uid),
            movie_id=int(mid)
        )
        db.session.add(moviecol)
        db.session.commit()
        data = dict(ok=1)
    import json
    return json.dumps(data)


# 电影收藏
@home.route("/moviecol/<int:page>/")
@user_login_req
def moviecol(page):
    if page is None:
        page = 1
    page_data = Moviecol.query.join(Movie).join(User).filter(
        Movie.id==Moviecol.movie_id,User.id==exist['user_id']
    ).order_by(
        Moviecol.addtime.desc()
    ).paginate(page=page, per_page=8)
    return render_template("home/moviecol.html",page_data=page_data)


@home.route("/animation")
def animation():
    data = Preview.query.all()
    length = len(data)
    return render_template("home/animation.html", data=data, len=length)


# 搜索电影
@home.route("/search/<int:page>", methods=['GET', 'POST'])
def search(page=None):
    if page is None:
        page = 1
    key = request.args.get("key", "")
    movie_count = Movie.query.filter(
        Movie.title.ilike('%' + key + '%')
    ).count()
    page_data = Movie.query.filter(
        Movie.title.ilike('%' + key + '%')
    ).order_by(
        Movie.addtime.desc()
    ).paginate(page=page, per_page=8)
    return render_template("home/search.html", key=key, page_data=page_data, movie_count=movie_count)


@home.route("/play/<int:id>/<int:page>", methods=['GET', 'POST'])
@user_login_req
def play(id=None, page=None):
    movie_comment_num = Comment.query.join(
        Movie
    ).filter(
        Movie.id == int(id),
    ).count()
    movie = Movie.query.join(Tag).filter(
        Tag.id == Movie.tag_id,
        Movie.id == int(id)
    ).first_or_404()
    if page is None:
        page = 1
    page_data = Comment.query.join(
        Movie
    ).join(
        User
    ).filter(
        Movie.id == movie.id,
        User.id == Comment.user_id
    ).order_by(
        Comment.addtime.desc()
    ).paginate(page=page, per_page=10)
    movie.playnum = movie.playnum + 1
    form = CommentForm()
    if form.validate_on_submit():
        data = form.data
        comment = Comment(
            content=data['content'],
            movie_id=movie.id,
            user_id=exist['user_id']
        )
        db.session.add(comment)
        db.session.commit()

app/app/templates/home/home.html
<!doctype html>
<html lang="zh-CN">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="renderer" content="webkit">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
	<title>微电影</title>
	<link rel="shortcut icon" href="{{ url_for('static',filename='tpl/static/base/images/logo.png') }}">
	<link rel="stylesheet" href="{{ url_for('static',filename='tpl/static/base/css/bootstrap.min.css') }}">
	<link rel="stylesheet" href="{{ url_for('static',filename='tpl/static/base/css/bootstrap-movie.css') }}">
	<link rel="stylesheet" href="{{ url_for('static',filename='tpl/static/base/css/animate.css') }}">
	<style>
        .navbar-brand>img {
            display: inline;
        }
        .media{
            padding:3px;
            border:1px solid #ccc
        }

	</style>
	{% block css %}
	{% endblock %}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
	<div class="container">
		<!--小屏幕导航按钮和logo-->
		<div class="navbar-header">
			<button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a href="{{ url_for('home.index',page=1) }}" class="navbar-brand" style="width:250px;">
				<img src="{{ url_for('static',filename='tpl/static/base/images/logo.png') }}" style="height:30px;">&nbsp;微电影
			</a>
		</div>
		<!--小屏幕导航按钮和logo-->
		<!--导航-->
		<div class="navbar-collapse collapse">
			<form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
				<div class="form-group input-group">
					<input type="text" class="form-control" placeholder="请输入电影名!" id="key_movie">
					<span class="input-group-btn">
                        <a class="btn btn-default" id="do_search"><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
				</div>
			</form>
			<ul class="nav navbar-nav navbar-right">
				<li>
					<a class="curlink" href="{{ url_for('home.index',page=1) }}"><span
							class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
				</li>
				<li>
					<a class="curlink" href="{{ url_for('home.regist') }}"><span
							class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
				</li>
				<li>
					<a class="curlink" href="{{ url_for('home.user') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
				</li>
				<li>
					<a class="curlink" href="{{ url_for('home.logout') }}"><span
							class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
				</li>
			</ul>
		</div>
		<!--导航-->

	</div>
</nav>
<!--导航-->
<!--内容-->
<div class="container" style="margin-top:76px">
	{% block content %}{% endblock %}
</div>
<!--内容-->
<!--底部-->
<footer>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<p>
					©&nbsp;2020 这是沐沐的第一个网站
				</p>
			</div>
		</div>
	</div>
</footer>
<!--底部-->
<script src="{{ url_for('static',filename='tpl/static/base/js/jquery.min.js') }}"></script>
<script src="{{ url_for('static',filename='tpl/static/base/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static',filename='tpl/static/base/js/jquery.singlePageNav.min.js') }}"></script>
<script src="{{ url_for('static',filename='tpl/static/base/js/wow.min.js') }}"></script>
<script src="{{ url_for('static',filename='tpl/static/lazyload/jquery.lazyload.min.js') }}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function() {
        new WOW().init();
    })


</script>
<script>
    $(document).ready(function() {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
        $("#do_search").click(function(){
        	var key=$("#key_movie").val();
        	location.href = "{{ url_for('home.search',page=1) }}?key=" +key;
        });
    });


</script>
{% block js %}{% endblock %}
</body>
</html>

app/app/templates/home/layout.html
<!doctype html>
<html lang="zh-CN">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="renderer" content="webkit">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
	<title>微电影</title>
	<link rel="shortcut icon" href="{{ url_for('static',filename='tpl/static/base/images/logo.png') }}">
	<link rel="stylesheet" href="{{ url_for('static',filename='tpl/static/base/css/bootstrap.min.css') }}">
	<link rel="stylesheet" href="{{ url_for('static',filename='tpl/static/base/css/bootstrap-movie.css') }}">
	<link rel="stylesheet" href="{{ url_for('static',filename='tpl/static/base/css/animate.css') }}">
	<style>
        .navbar-brand>img {
            display: inline;
        }
        .media{
            padding:3px;
            border:1px solid #ccc
        }



	</style>
	{% block css %}{% endblock %}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
	<div class="container">
		<!--小屏幕导航按钮和logo-->
		<div class="navbar-header">
			<button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a href="{{ url_for('home.index',page=1) }}" class="navbar-brand" style="width:250px;">
				<img src="{{ url_for('static',filename='tpl/static/base/images/logo.png') }}" style="height:30px;">&nbsp;微电影
			</a>
		</div>
		<!--小屏幕导航按钮和logo-->
		<!--导航-->
		<div class="navbar-collapse collapse">
			<form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
				<div class="form-group input-group">
					<input type="text" class="form-control" placeholder="请输入电影名！" id="key_movie">
					<span class="input-group-btn">
                        <a class="btn btn-default" id="do_search"><span
								class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
				</div>
			</form>
			<ul class="nav navbar-nav navbar-right">
				<li>
					<a class="curlink" href="{{ url_for('home.index',page=1) }}"><span
							class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
				</li>
				{% if not exist %}
				<li>
					<a class="curlink" href="{{ url_for('home.login') }}"><span
							class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
				</li>
				<li>
					<a class="curlink" href="{{ url_for('home.regist') }}"><span
							class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
				</li>
				{% endif %}
				{% if exist %}
				<li>
					<a class="curlink" href="{{ url_for('home.user') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;会员中心</a>
				</li>
				{% endif %}
				{% if exist %}
				<li>
					<a class="curlink" href="{{ url_for('home.logout') }}"><span
							class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
				</li>
				{% endif %}
			</ul>
		</div>
		<!--导航-->

	</div>
</nav>
<!--导航-->
<!--内容-->
{% block content %}{% endblock %}
</div>
<!--内容-->
<!--底部-->
<footer>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<p>
					©&nbsp;2020 这是沐沐的第一个网站
				</p>
			</div>
		</div>
	</div>
</footer>
<!--底部-->
<script src="{{ url_for('static',filename='tpl/static/base/js/jquery.min.js') }}"></script>
<script src="{{ url_for('static',filename='tpl/static/base/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static',filename='tpl/static/base/js/jquery.singlePageNav.min.js') }}"></script>
<script src="{{ url_for('static',filename='tpl/static/base/js/wow.min.js') }}"></script>
<script src="{{ url_for('static',filename='tpl/static/lazyload/jquery.lazyload.min.js') }}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function() {
        new WOW().init();
    })




</script>
<script>
    $(document).ready(function() {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
        $("#do_search").click(function(){
        	var key=$("#key_movie").val();
        	location.href = "{{ url_for('home.search',page=1) }}?key="+key;
        });
    });




</script>
{% block js %}{% endblock %}
</body>
</html>

app/app/templates/home/menu.html
<div class="col-md-3">
		<div class="list-group">
			<a id='m-1' href="{{ url_for('home.user') }}"  class="list-group-item">
				<span class="glyphicon glyphicon-user"></span>&nbsp;会员中心
			</a>
			 <a id='m-2' href="{{ url_for('home.pwd') }}" class="list-group-item">
				<span class="glyphicon glyphicon-lock"></span>&nbsp;修改密码
			</a>
			<a id='m-3' href="{{ url_for('home.comments',page=1) }}" class="list-group-item">
				<span class="glyphicon glyphicon-comment"></span>&nbsp;评论记录
			</a>
			<a id='m-4' href="{{ url_for('home.loginlog',page=1) }}" class="list-group-item">
				<span class="glyphicon glyphicon-calendar"></span>&nbsp;登录日志
			</a>
			<a id='m-5' href="{{ url_for('home.moviecol',page=1) }}" class="list-group-item">
				<span class="glyphicon glyphicon-heart"></span>&nbsp;收藏电影
			</a>
		</div>
</div>

app/app/templates/home/moviecol.html
{% extends "home/home.html" %}
{% import "ui/home_page.html" as pg %}

{% block css %}
<style>
	.col-lg-1, .col-lg-10, .col-lg-11, .col-lg-12, .col-lg-2, .col-lg-3, .col-lg-4, .col-lg-5, .col-lg-6, .col-lg-7, .col-lg-8, .col-lg-9, .col-md-1, .col-md-10, .col-md-11, .col-md-12, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7, .col-md-8, .col-md-9, .col-sm-1, .col-sm-10, .col-sm-11, .col-sm-12, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-xs-1, .col-xs-10, .col-xs-11, .col-xs-12, .col-xs-2, .col-xs-3, .col-xs-4, .col-xs-5, .col-xs-6, .col-xs-7, .col-xs-8, .col-xs-9{
            padding-right: 3px;
            padding-left: 3px;
        }



</style>
{% endblock %}

{% block content %}
{% include "home/menu.html" %}
<div class="col-md-9">
	<div class="panel panel-warning">
		<div class="panel-heading">
			<h3 class="panel-title"><span class="glyphicon glyphicon-map-marker"></span>&nbsp;收藏电影</h3>
		</div>
		<div class="panel-body">
			<div class="col-md-12">
				{% for v in page_data.items %}
				<div class="media">
					<div class="media-left">
						<a href="{{ url_for('home.play',page=1,id=v.movie_id) }}">
							<img class="media-object" style="width:131px;height:83px;"
								 src="{{ url_for('static',filename='uploads/'+v.movie.logo)}}" alt="{{ v.movie.title }}">
						</a>
					</div>
					<div class="media-body">
						<h4 class="media-heading">{{ v.movie.title }}<a
								href="{{ url_for('home.play',page=1,id=v.movie_id) }}"
								class="label label-primary pull-right"><span
								class="glyphicon glyphicon-play"></span>播放影片</a></h4>
								{{ v.movie.info }}
					</div>
				</div>
				{% endfor %}
			</div>
			<div class="col-md-12 text-center" style="margin-top:6px;">
				{{ pg.page(page_data,'home.moviecol') }}

			</div>
		</div>
	</div>
</div>
{% endblock %}
{% block js %}
<script>
	$(document).ready(function(){
		$("#m-5").addClass("active");
	})



</script>
{% endblock %}